# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [83]:
import numpy as np
import pandas as pd

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [84]:
df = pd.DataFrame({
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
})

df

    Name  Age         City
0   John   16     New York
1  Emily   28  Los Angeles
2   Ryan   22      Chicago

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [85]:
df["Age"]

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [86]:
salary = pd.Series([50000, 60000, 45000], name="Salary")
df["Salary"] = salary
df

    Name  Age         City  Salary
0   John   16     New York   50000
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [87]:
df[df["Age"] > 18]

    Name  Age         City  Salary
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [88]:
df["Birth year"] = 2026 - df["Age"]
df

    Name  Age         City  Salary  Birth year
0   John   16     New York   50000        2010
1  Emily   28  Los Angeles   60000        1998
2   Ryan   22      Chicago   45000        2004

### Task 4.2

Add new calculated field `Average age`.

In [89]:
df["Average age"] = sum(df["Age"]) / df["Age"].count()
df

    Name  Age         City  Salary  Birth year  Average age
0   John   16     New York   50000        2010         22.0
1  Emily   28  Los Angeles   60000        1998         22.0
2   Ryan   22      Chicago   45000        2004         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [90]:
abs(df["Age"] - df["Average age"])

0    6.0
1    6.0
2    0.0
dtype: float64

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [91]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [92]:
pd.merge(df1, df2)

    Name  Age         City
0  Emily   28  Los Angeles
1   Ryan   22      Chicago

In [93]:
pd.concat([df1, df2])

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
0  Emily   NaN  Los Angeles
1   Ryan   NaN      Chicago
2   Mike   NaN      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [94]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [95]:
s = s1 + s2

In [96]:
s = s1 - s2

In [97]:
s = s1 * s2

In [98]:
s = s1 / s2

In [99]:
s = s1 ** s2

In [100]:
s = s1 // s2

In [101]:
s = s1 % s2

In [102]:
s1[s1 % 2 == 0]

1    2
3    4
dtype: int64

In [103]:
s2[s2 % 2 == 1]

1    7
3    9
dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [104]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [105]:
upper = s.str.upper()

In [106]:
lengths = s.str.len()

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [107]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

CPU times: user 2.06 s, sys: 63.6 ms, total: 2.12 s
Wall time: 2.13 s

[42.8, 50.4, 36.2, 35.0, 44.0, 54.0, 63.2, 59.6, 56.6, 41.4]

### Solution using Pandas and Numpy

In [108]:
data = np.random.randint(1, 101, 10_000_000)

# 1. Згортка (convolution)
ma_conv = np.convolve(data, np.ones(5) / 5, mode="valid")

# 2. Кумулятивна сума (найшвидший варіант)
cs = np.cumsum(data, dtype=np.int64)
cs[5:] = cs[5:] - cs[:-5]
ma_cumsum = cs[4:] / 5

# 3. Ковзні вікна (найчитабільніший)
from numpy.lib.stride_tricks import sliding_window_view
ma_view = sliding_window_view(data, 5).mean(axis=1)

s = pd.Series(data)

print(np.allclose(ma_conv, ma_cumsum), np.allclose(ma_conv, ma_view))
print(np.allclose(ma_conv, s.rolling(5).mean().dropna().to_numpy()))

%timeit s.rolling(5).mean().dropna()
%timeit np.convolve(data, np.ones(5) / 5, mode="valid")
%timeit sliding_window_view(data, 5).mean(axis=1)

True True
True
66.7 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
7.9 ms ± 259 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
72.4 ms ± 192 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)